//
//  StringScheme.swift
//  WeatherApp
//
import UIKit

struct StringConstants {
    static let k: String = ""
    static let kLblThu: String = "Thu"
    static let kLbl604Am: String = "6:04 am"
    static let kLblAlerts: String = "Alerts"
    static let kMsgConditionsAre: String =
        "Conditions are favourable for the development of severe thunderstorms that may be capable of producing strong wind gusts, large hail and heavy rain.\n\nStrong wind gusts can toss loose objects, damage weak buildings, break branches off trees and overturn large vehicles. Heavy downpours can cause flash floods and water pooling on roads.\n\nSevere thunderstorm watches are issued when atmospheric conditions are favourable for the development of thunderstorms that could produce one or more of the following: large hail, damaging winds, torrential rainfall.\n\nPlease continue to monitor alerts and forecasts issued by Environment Canada. To report severe weather, send an email to ONstorm@ec.gc.ca or tweet reports using #QCStorm."
    static let kLblN: String = "N"
    static let kLblPartlyCloudy: String = "Partly cloudy."
    static let kLbl649Pm: String = "6:49 pm"
    static let kLblGoa: String = "Goa"
    static let kMsgSalemiSicilia: String = "Salemi, Sicilia, Italy"
    static let kLbl18C: String = "18°c"
    static let kLbl12C: String = "12°c"
    static let kLbl10C: String = "10°c"
    static let kMsgSalemOregon: String = "Salem, Oregon, United States of America"
    static let kMsgCurrentLocatio: String = "Current Location"
    static let kLblThunderstorm: String = "Thunderstorm"
    static let kLblOttawa: String = "Ottawa"
    static let kLbl900Am: String = "9:00 am"
    static let kLblToday: String = "Today"
    static let kLblBengaluru: String = "Bengaluru"
    static let kLbl200Am: String = "2:00 am"
    static let kMsgSalemTamilNa: String = "Salem, Tamil Nadu, India"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLblSat: String = "Sat"
    static let kLbl60: String = "6.0"
    static let kMsgSalemOhioUn: String = "Salem, Ohio, United States of America"
    static let kMsg21Jul20238: String = "21 Jul, 2023 8:00 pm -  29 Jul, 2023 9:00 pm"
    static let kLbl28C: String = "28°c"
    static let kLblWind: String = "Wind"
    static let kLbl24C: String = "24°c"
    static let kLblSnow: String = "Snow"
    static let kLbl22C: String = "22°c"
    static let kLbl19: String = "19"
    static let kLbl20C: String = "20°c"
    static let kLblNow: String = "Now"
    static let kLblWed: String = "Wed"
    static let kMsgOnstormEcGcC: String = "ONstorm@ec.gc.ca"
    static let kLblSun: String = "Sun"
    static let kLblSnowCanada: String = "Snow Canada"
    static let kLblC: String = "°c"
    static let kMsgSearchForACi: String = "Search for a city or US/UK zip to check the weather"
    static let kLblFeelsLike20C: String = "feels like 20°c"
    static let kLbl5DayForecast: String = "5-day forecast"
    static let kMsgOrTweetReport: String = " or tweet reports using #QCStorm."
    static let kLblRemove: String = "Remove"
    static let kLbl3: String = "3"
    static let kLbl19C: String = "19°c"
    static let kLbl4: String = "4"
    static let kLblPrecipitation: String = "Precipitation"
    static let kLbl5: String = "5"
    static let kLbl6: String = "6"
    static let kLbl17C: String = "17°c"
    static let kLbl7: String = "7"
    static let kLbl8: String = "8"
    static let kMsgSalemSaintPe: String = "Salem, Saint Peter, Montserrat"
    static let kLbl11C: String = "11°c"
    static let kLblBerlin: String = "Berlin"
    static let kLblDelete: String = "Delete"
    static let kMsgConditionsAre3: String =
        "Conditions are favourable for the development of severe thunderstorms that may be capable of producing strong wind gusts, large hail and heavy rain and Snow."
    static let kMsgEnvironmentCan: String = "Environment Canada"
    static let kMsgConditionsAre2: String =
        "Conditions are favourable for the development of severe thunderstorms that may be capable of producing strong wind gusts, large hail and heavy rain.\n\nStrong wind gusts can toss loose objects, damage weak buildings, break branches off trees and overturn large vehicles. Heavy downpours can cause flash floods and water pooling on roads.\n\nSevere thunderstorm watches are issued when atmospheric conditions are favourable for the development of thunderstorms that could produce one or more of the following: large hail, damaging winds, torrential rainfall.\n\nPlease continue to monitor alerts and forecasts issued by Environment Canada. To report severe weather, send an email to "
    static let kLbl295Kph: String = "29.5 kph"
    static let kLbl1200Am: String = "12:00 am"
    static let kHttpFail: String = "HTTP request failed"
    static let kMsgKarnatakaIndi: String = "Karnataka, India"
    static let kLblAdd: String = "+ Add"
    static let kLblUvIndex: String = "UV index"
    static let kMsgCityRegionOr: String = "City, Region or US/UK zip code"
    static let kLblSalem: String = "Salem"
    static let kLblFri: String = "Fri"
    static let kLbl18Mm: String = "1.8 mm"
    static let kLbl23C: String = "23°c"
    static let kLblOntarioCanada: String = "Ontario, Canada"
    static let kLblWeatherApp: String = "Weather App"
    static let kLbl21C: String = "21°c"
    static let kInvalidUrl: String = "Invalid URL"
    static let kLblBerlinGermany: String = "Berlin, Germany"
}
